name = "ddsr-dashboard"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "ddsr_dashboard"
database_name = "ddsr-dashboard"
database_id = "881a5b84-edee-4872-bede-a01b21e1bc1f"
