PRAGMA foreign_keys = OFF;

-- ── TASKS ─────────────────────────────────────────────────────────────────
-- workflow_id: 1=Vic.AI/AP  2=MOLO  3=Purchasing  4=Paylocity  5=Financial  6=SysConfig
-- assignee_id: 1=Adina 2=Gretchen 3=Jenna 4=Leslie 5=Stephanie 6=Nicole 7=Cheri
--              8=NetSuite Implementation  9=MOLO Team  10=Vic.AI Team

INSERT INTO tasks (project_id, workflow_id, assignee_id, assignee_name, title, status, priority, due_date) VALUES
-- ── Vic.AI / AP ────────────────────────────────────────────────────────────
(1,1,4,'Leslie','Follow up on two open Vic.ai issues with Vivian','Not Started','','2026-04-28'),
(1,1,4,'Leslie','Repost the canceled invoices once Vivian confirms','Not Started','','2026-05-05'),
(1,1,4,'Leslie','Repost all invoices in a Posting Failed state','Not Started','','2026-05-07'),
(1,1,5,'Stephanie','Report on Vic AI progress after the call with the vendor','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Fix the discount display error in Vic.ai','Not Started','','2026-04-22'),
(1,1,10,'Vic.AI Team','Provide the public dashboard link for vendor onboarding','Not Started','','2026-04-24'),
(1,1,10,'Vic.AI Team','Upload initial vendor ACH details','Not Started','','2026-04-24'),
(1,1,10,'Vic.AI Team','Confirm vendor credit sync logic before Thursday','Not Started','','2026-04-27'),
(1,1,10,'Vic.AI Team','Follow up with support on the processing screen glitch','Not Started','','2026-04-30'),
(1,1,10,'Vic.AI Team','Follow up with Julian on the duplicate posting error','Not Started','','2026-04-30'),
(1,1,10,'Vic.AI Team','Provide Peter with the list of affected Sightline POs','Not Started','','2026-04-30'),
(1,1,10,'Vic.AI Team','Investigate the root cause of the spinning invoices','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Cancel all spinning invoices','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Manually clear all duplicate posting errors','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Follow up on the IT screen-glitching ticket','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Confirm vendor campaign status with Katie','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Schedule an analytics session with Jack','Not Started','','2026-05-05'),
(1,1,10,'Vic.AI Team','Confirm the system glitch fix release date and notify the team','Not Started','','2026-05-07'),
(1,1,10,'Vic.AI Team','Review accuracy reports with the ML team','Not Started','','2026-05-07'),
(1,1,10,'Vic.AI Team','Test the VRA process using the two new test VRAs','Not Started','','2026-05-07'),
(1,1,1,'Adina','Discuss the Vic AI bank reconciliation process','Not Started','','2026-04-01'),
(1,1,1,'Adina','Create the Vic AI AP process document for Nicoles team','Not Started','','2026-04-17'),
(1,1,1,'Adina','Define the process for handling Sightline credits','Not Started','','2026-04-21'),
(1,1,1,'Adina','Develop a process for applying credits to Sightline POs','Not Started','','2026-04-22'),
(1,1,1,'Adina','Update Item Account data in the Sightline source file','Not Started','','2026-04-30'),
(1,1,8,'NetSuite Implementation','Reclass all incorrect inventory bill postings to new Vouchers Payable account','Not Started','','2026-05-07'),
(1,1,8,'NetSuite Implementation','Run the script to update bill dates to April 27','Not Started','','2026-04-30'),
(1,1,3,'Jenna','Review and manually correct other non-inventory Vic AI bill postings','Not Started','','2026-05-07'),
(1,1,8,'NetSuite Implementation','Run script to fix incorrect invoice dates from Vic.ai','Not Started','','2026-04-27'),
-- ── MOLO Integration ───────────────────────────────────────────────────────
(1,2,1,'Adina','Location Balancing Testing','In Progress','','2026-02-25'),
(1,2,1,'Adina','Mapping Fix Molo NetSuite Inventory Items and Other GL Codes','In Progress','','2026-02-25'),
(1,2,1,'Adina','Item List Sync Molo to NetSuite','In Progress','','2026-02-25'),
(1,2,1,'Adina','Customer List Data Review - Missing customers','In Progress','','2026-02-25'),
(1,2,1,'Adina','Molo Boat Record Review','In Progress','','2026-02-25'),
(1,2,1,'Adina','Ownership History Review','In Progress','','2026-02-25'),
(1,2,1,'Adina','Confirm with Jenna the MOLO VRMA workflow is acceptable','Not Started','','2026-03-13'),
(1,2,1,'Adina','Follow up with Dimitri on item and customer list data','Not Started','','2026-04-07'),
(1,2,1,'Adina','Confirm AR ledger tie-out against Molo report','Not Started','','2026-04-28'),
(1,2,1,'Adina','Review inventory tie-out for all sites','Not Started','','2026-04-28'),
(1,2,1,'Adina','Investigate the item receipt incorrectly hitting the Direct Materials GL','Not Started','','2026-05-05'),
(1,2,1,'Adina','Ask Peter to re-upload the 82670 record history file','Not Started','','2026-05-05'),
(1,2,1,'Adina','Finalize the list of accounting issues before sending to the Molo team','Not Started','','2026-05-10'),
(1,2,1,'Adina','Discuss the internal WO cost capture issue with Jenna','Not Started','','2026-05-10'),
(1,2,1,'Adina','Create a consolidated list of critical vs Phase 2 items for Dan','Not Started','','2026-05-05'),
(1,2,9,'MOLO Team','Fix the Molo job type sync issue','Not Started','','2026-04-28'),
(1,2,9,'MOLO Team','Investigate why labor costs are not syncing on internal invoices','Not Started','','2026-04-28'),
(1,2,9,'MOLO Team','Implement the band-aid WIP fix','Not Started','','2026-05-05'),
(1,2,9,'MOLO Team','Investigate and fix the LOA UoM mapping error','Not Started','','2026-05-05'),
(1,2,9,'MOLO Team','Continue to work around the WIP and LOA bugs','Not Started','','2026-05-10'),
(1,2,9,'MOLO Team','Contact Dan Nelson at Molo for timeline on Work Order to PO workflow','Not Started','','2026-04-01'),
(1,2,9,'MOLO Team','Discuss the boat record data priority with Andrew','Not Started','','2026-04-06'),
(1,2,9,'MOLO Team','Email GMs to coordinate with service managers on collecting missing vessel data','Not Started','','2026-03-31'),
(1,2,9,'MOLO Team','Remove Molo PO and Vendor Bill permissions pending review of the sublet workflow','Not Started','','2026-04-13'),
(1,2,9,'MOLO Team','Discuss the item type sync logic with Patrick','Not Started','','2026-04-07'),
(1,2,9,'MOLO Team','Confirm the GL impact of MOLO negative inventory feature','Not Started','','2026-03-27'),
(1,2,9,'MOLO Team','Confirm with Patrick if the intercompany type tag is flowing to NetSuite','Not Started','','2026-05-10'),
(1,2,1,'Adina','Schedule a call with Harrison to clarify MOLO transaction reversals','Not Started','','2026-04-23'),
(1,2,1,'Adina','Investigate the 50k non-inventory item account balance in MOLO','Not Started','','2026-04-23'),
(1,2,1,'Adina','Schedule a call to define the post-go-live reconciliation process','Not Started','','2026-04-23'),
(1,2,1,'Adina','Schedule a meeting to define the WIP accounting model','Not Started','','2026-04-26'),
(1,2,1,'Adina','Provide go-ahead to Patrick and Harrison for MOLO data cutover','Not Started','','2026-04-23'),
-- May 14 MOLO tasks
(1,2,1,'Adina','Email Patrick (MOLO) consolidated bug list — purchase price sync, sublet search, LOA, WIP, date stamps, WO job types','Not Started','High','2026-05-14'),
(1,2,1,'Adina','Call Brian re: Stanford MOLO launch — escalate risks and decision; update Steven + Harrison','Not Started','High','2026-05-14'),
(1,2,8,'NetSuite Implementation','Investigate NetSuite inventory bump for item 15422781 on May 4 8:21 AM — report findings','Not Started','','2026-05-14'),
(1,2,1,'Adina','Email Peter Bratzis (IT) re: SightLine valuation report — confirm whether it includes WIP and confirm cutover approach','Not Started','','2026-05-14'),
(1,2,1,'Adina','Confirm with SightLine that all open work orders and WIP will be closed before Stanford migration','Not Started','','2026-05-14'),
-- ── NetSuite Purchasing ────────────────────────────────────────────────────
(1,3,8,'NetSuite Implementation','Allocation Schedule Dept Update','Not Started','','2026-02-20'),
(1,3,8,'NetSuite Implementation','Create the custom FOB field on the vendor record','Not Started','','2026-04-21'),
(1,3,8,'NetSuite Implementation','Move PO line fields Location Department to the end of the line','Not Started','','2026-04-23'),
(1,3,8,'NetSuite Implementation','Move item record fields MOLO BIN Purchase Price to the top','Not Started','','2026-04-23'),
(1,3,8,'NetSuite Implementation','Wipe the production environment and notify Patrick to begin the MOLO sync','Not Started','','2026-04-23'),
(1,3,8,'NetSuite Implementation','Initiate the Sandbox refresh','Not Started','','2026-04-23'),
(1,3,8,'NetSuite Implementation','Execute the cutover plan on Monday AM','Not Started','','2026-04-23'),
(1,3,8,'NetSuite Implementation','Import item data fixes missing base pricing non-inventory setup','Not Started','','2026-04-26'),
(1,3,8,'NetSuite Implementation','Lock April AP and AR periods in NetSuite tonight','Not Started','','2026-04-26'),
(1,3,8,'NetSuite Implementation','Import MOLO inventory files as NetSuite adjustments','Not Started','','2026-04-27'),
(1,3,8,'NetSuite Implementation','Create P&I Item checkbox on the inventory item form','Not Started','','2026-04-27'),
(1,3,8,'NetSuite Implementation','Add the Payment Method field to the bill payment form','Not Started','','2026-05-05'),
(1,3,4,'Leslie','Update the cheat sheet with NetSuite codes and distribute to purchasers','Not Started','','2026-04-28'),
(1,3,4,'Leslie','Update preferences Number of Rows in List Segments to 1000','Not Started','','2026-05-05'),
(1,3,4,'Leslie','Customize dashboards using Reminders Shortcuts and Custom Content portlets','Not Started','','2026-05-05'),
(1,3,6,'Nicole','Re-attempt the TB import after balancing','Not Started','','2026-03-12'),
(1,3,6,'Nicole','Build separate allocation schedules for all required GL accounts','Not Started','','2026-03-31'),
(1,3,6,'Nicole','Consult Joshua Sightline on the non-inventory PO GL impact timing','Not Started','','2026-03-27'),
(1,3,1,'Adina','Create the custom bin location table on the item record','Not Started','','2026-04-23'),
(1,3,1,'Adina','Follow up with Harrison to add the location-specific BIN to the PO PDF','Not Started','','2026-04-24'),
(1,3,1,'Adina','Notify Peter to automate the Sightline PO file export','Not Started','','2026-04-21'),
(1,3,1,'Adina','Create a saved search to flag transactions posted to prior periods','Not Started','','2026-04-28'),
(1,3,1,'Adina','Train Stephanie and Leslie on NetSuite batch check runs','Not Started','','2026-04-23'),
(1,3,1,'Adina','Send calendar invite for the April 22nd training session','Not Started','','2026-04-21'),
(1,3,2,'Gretchen','Create the purchasing cheat sheet with FAQs from Chad and Steven','Not Started','','2026-04-21'),
-- May 14 purchasing tasks
(1,3,8,'NetSuite Implementation','Update margin report — invoice-level detail; filter Retail; exclude Internal; add WO job type column; email team','Not Started','','2026-05-14'),
(1,3,1,'Adina','Lead UOM standardization project — convert items to smallest issued unit, populate Order Multiple field','Not Started','','2026-05-14'),
-- ── Paylocity / Concur ────────────────────────────────────────────────────
(1,4,5,'Stephanie','Test Paylocity integration and get sign-off from Nicole and Jenna','Not Started','','2026-03-31'),
(1,4,5,'Stephanie','Test Concur import with Gretchen once Nicole provides GL specs','Not Started','','2026-03-31'),
(1,4,5,'Stephanie','Email VIT to remove the CLIENT NAME department from the system','Not Started','','2026-05-07'),
(1,4,2,'Gretchen','Paylocity and NetSuite UAT Testing and Flow','In Progress','','2026-02-25'),
(1,4,2,'Gretchen','Review the test Paylocity journal entry with Jenna','Not Started','','2026-03-27'),
(1,4,2,'Gretchen','Work with Stephanie to configure the custom PO column in Concur','Not Started','','2026-03-31'),
-- ── Financial Close ────────────────────────────────────────────────────────
(1,5,2,'Gretchen','Trial Balance Review Summary','Not Started','','2026-02-25'),
(1,5,2,'Gretchen','Management Report Creation','Not Started','','2026-02-25'),
(1,5,2,'Gretchen','Attend the meeting with Nicole to clarify production RevRec needs','Not Started','','2026-03-27'),
(1,5,2,'Gretchen','Complete historical balance sheet imports once the system is stable','Not Started','','2026-03-27'),
(1,5,2,'Gretchen','Add indirect expense GLs to the chart of accounts','Not Started','','2026-04-01'),
(1,5,2,'Gretchen','Send the final management package PDF to Adina','Not Started','','2026-04-17'),
(1,5,2,'Gretchen','Schedule the R2R review with Adina for Monday','Not Started','','2026-04-17'),
(1,5,2,'Gretchen','Begin building financial schedules as Saved Searches','Not Started','','2026-04-21'),
(1,5,2,'Gretchen','Confirm Divyas Molo report email is redirected to Jenna','Not Started','','2026-05-05'),
(1,5,2,'Gretchen','Restructure the COA rename inactivate and group accounts','Not Started','','2026-05-07'),
(1,5,2,'Gretchen','Update import mappings to reflect new account IDs','Not Started','','2026-05-07'),
(1,5,2,'Gretchen','Rename and remove incorrect reports in NetSuite','Not Started','',NULL),
(1,5,2,'Gretchen','Contact Harrison for help building the final report set','Not Started','',NULL),
(1,5,2,'Gretchen','Test Claude AI for data cleanup','Not Started','',NULL),
(1,5,2,'Gretchen','Investigate the 100% prepayment workflow with the team','Not Started','','2026-04-01'),
(1,5,2,'Gretchen','NetSuite Reports Build for Jenna Service P&L Statements','Not Started','','2026-02-25'),
(1,5,2,'Gretchen','Clean up obsolete locations in NetSuite','Not Started','','2026-03-12'),
(1,5,3,'Jenna','Confirm REVREC Package Hierarchy','Not Started','','2026-02-19'),
(1,5,3,'Jenna','Discuss Inventory Costing Molo','Not Started','','2026-02-19'),
(1,5,3,'Jenna','Review NetSuite allocations with Adina and Gretchen','Not Started','','2026-04-10'),
(1,5,3,'Jenna','Tag all open work orders for intercompany functionality','Not Started','','2026-04-21'),
(1,5,3,'Jenna','Create and distribute the new AP process communication','Not Started','','2026-04-23'),
(1,5,3,'Jenna','Review Harrison inventory opening balance files for accuracy','Not Started','','2026-04-28'),
(1,5,3,'Jenna','Join the revenue allocation call with Nicole and Harrison','Not Started','','2026-05-05'),
(1,5,3,'Jenna','Send the internal customers report to Laura for review','Not Started','','2026-05-05'),
(1,5,3,'Jenna','Request Peters Sightline export file to fix the GL mapping error','Not Started','','2026-05-07'),
(1,5,3,'Jenna','Schedule a meeting with Brian to discuss pausing the Molo go-live','Not Started','','2026-05-07'),
(1,5,3,'Jenna','Continue using manual journal entry workaround for internal labor costs','Not Started','','2026-05-10'),
(1,5,8,'NetSuite Implementation','Lock the NetSuite period ending April 26 on Monday','Not Started','','2026-04-24'),
(1,5,8,'NetSuite Implementation','Post the GL reversal journal entry on Monday morning','Not Started','','2026-04-24'),
(1,5,8,'NetSuite Implementation','Create the revenue allocation report for packages','Not Started','','2026-05-05'),
(1,5,8,'NetSuite Implementation','Finalize the general ledger report for transaction tracking','Not Started','','2026-05-05'),
(1,5,8,'NetSuite Implementation','Investigate and consolidate all temporary deferred revenue activity into account 2818','Not Started','','2026-05-10'),
(1,5,8,'NetSuite Implementation','Automate the daily running of Revenue Arrangements for account 2818','Not Started','','2026-05-10'),
(1,5,1,'Adina','Sync Gretchen and Jenna to align on reporting needs','In Progress','','2026-03-10'),
(1,5,1,'Adina','Build financial schedules as Saved Searches to assist Gretchen','Not Started','','2026-04-21'),
(1,5,1,'Adina','Define the post-go-live balance sheet import process with Gretchen','Not Started','','2026-04-06'),
(1,5,1,'Adina','Schedule a 1-on-1 with Jenna for Monday to discuss GL flow','Not Started','','2026-04-17'),
(1,5,1,'Adina','Request creation of the Intercompany Clearing GL account in NetSuite','Not Started','','2026-04-22'),
(1,5,1,'Adina','Propose a name for the new Molo payment type','Not Started','','2026-04-22'),
(1,5,1,'Adina','Review the proposed AR and AP clearing process with Nicole and Brian','Not Started','','2026-04-22'),
(1,5,1,'Adina','Confirm the intercompany job checkbox will correctly route revenue','Not Started','','2026-04-22'),
(1,5,1,'Adina','Define the final workflow for routing intercompany invoices for coding','Not Started','','2026-04-22'),
(1,5,1,'Adina','Email Gretchen to rename GL 2818 to Temporary Deferred Revenue','Not Started','','2026-04-21'),
(1,5,1,'Adina','Research native NetSuite prepayment features','Not Started','','2026-05-07'),
(1,5,1,'Adina','Discuss prepayment tracking on next weeks agenda','Not Started','','2026-05-07'),
-- ── System Config ──────────────────────────────────────────────────────────
(1,6,1,'Adina','Lock down GL creation and changes in NetSuite to Lou and Gretchen','In Progress','','2026-03-04'),
(1,6,1,'Adina','Confirm the UAT sandbox timeline with the BCC team','Not Started','','2026-04-21'),
(1,6,1,'Adina','Request correct NetSuite roles for Leslie and Tracy from Gretchen','Not Started','','2026-04-21'),
(1,6,1,'Adina','Pause direct problem-reporting to the AP team for 3-4 days','Not Started','','2026-05-07'),
(1,6,1,'Adina','Propose an enterprise Claude license to Brian','Not Started','','2026-05-07'),
(1,6,1,'Adina','Enable the Exception Management portlet on user dashboards','Not Started','','2026-05-05'),
(1,6,1,'Adina','Create the custom NetSuite saved search for GL activity','Not Started','','2026-05-05'),
(1,6,1,'Adina','Correct the GL account mapping in NetSuite asset vs liability','Not Started','','2026-05-07'),
(1,6,1,'Adina','Build rules in NetSuite to auto-map transactions to correct GLs','Not Started','','2026-05-10'),
(1,6,1,'Adina','Notify Harrison of the Base Price script error and missing System Information tab','Not Started','','2026-05-10'),
(1,6,1,'Adina','Consult Jenna on the GL impact of the non-tracked item bug','Not Started','','2026-04-06'),
(1,6,8,'NetSuite Implementation','Investigate the new native Outlook sync connector','Not Started','','2026-05-05'),
(1,6,8,'NetSuite Implementation','Enable Exception Management for Hinckley','Not Started','','2026-05-05'),
(1,6,2,'Gretchen','Select appropriate variance GLs for the Post Vendor Bill Variances tool','Not Started','','2026-05-07'),
(1,6,7,'Cheri','Report any sync failures that occur after a 5-minute delay','Not Started','','2026-05-10'),
-- May 14 system config task
(1,6,1,'Adina','Propose Claude team plan + NetSuite MCP Connector to Brian','Not Started','','2026-05-14');

PRAGMA foreign_keys = ON;
